### ISSUE TITLE
Inconsistent behavior between iOS and Android sampler app

### ISSUE THREAD

**Issue by viveksekar** [ConnectSDK/Connect-SDK-Android-API-Sampler#11]
The Android sampler app
does not switch between the actively playing media.
- Play Audio from sampler
- without closing, Play video from the sampler

App behavior 
- The audio is closed, but the video is not launched.
- Have to click the video button again to launch

**Comment by frolov-alexey** [comment]
This issues was fixed here https://github.com/ConnectSDK/Connect-SDK-Android-API-Sampler/commit/18848490b0bf60485f553106d87e022ba6fa76c5
