### ISSUE TITLE
Sample App doesnt request pairing key

### ISSUE THREAD

**Issue by zamirszn** [ConnectSDK/Connect-SDK-Android-API-Sampler#53]
i ran the sample app and it only connect with limited functionality (only media and volume control works) , i need to  implement the remote control feature for my app , ive gone through the docs on how to setup pairing with pin code , still didnt work with my tv , i tested some apps built with connectsdk and i was able to pair and use the remote control with my TV , can anyone help please ? am i missing something ?

**Comment by Avasara** [comment]
> i ran the sample app and it only connect with limited functionality (only media and volume control works) , i need to implement the remote control feature for my app , ive gone through the docs on how to setup pairing with pin code , still didnt work with my tv , i tested some apps built with connectsdk and i was able to pair and use the remote control with my TV , can anyone help please ? am i missing something ?

It's the same for me. I can connect to it and launch some apps but I want keyControl. The docs are not much help for that. I also noticed that it doesn't connect to multiple services for me. Is that the case for you? It connects to either DLNA or DIAL for me. NetCast requires pairing but it won't connect to that.

**Comment by zamirszn** [comment]
> > i ran the sample app and it only connect with limited functionality (only media and volume control works) , i need to implement the remote control feature for my app , ive gone through the docs on how to setup pairing with pin code , still didnt work with my tv , i tested some apps built with connectsdk and i was able to pair and use the remote control with my TV , can anyone help please ? am i missing something ?
> 
> It's the same for me. I can connect to it and launch some apps but I want keyControl. The docs are not much help for that. I also noticed that it doesn't connect to multiple services for me. Is that the case for you? It connects to either DLNA or DIAL for me. NetCast requires pairing but it won't connect to that.

yup same issue , do you know any other lib that can solve this issue ? this project looks abandoned, I tried decompiling an app that uses connectsdk and it looks like the pairing part wasn't done with connectsdk , it was  calling a Sony hardware library to pair

**Comment by Avasara** [comment]
> > > i ran the sample app and it only connect with limited functionality (only media and volume control works) , i need to implement the remote control feature for my app , ive gone through the docs on how to setup pairing with pin code , still didnt work with my tv , i tested some apps built with connectsdk and i was able to pair and use the remote control with my TV , can anyone help please ? am i missing something ?
> > 
> > It's the same for me. I can connect to it and launch some apps but I want keyControl. The docs are not much help for that. I also noticed that it doesn't connect to multiple services for me. Is that the case for you? It connects to either DLNA or DIAL for me. NetCast requires pairing but it won't connect to that.
> 
> yup same issue , do you know any other lib that can solve this issue ? this project looks abandoned, I tried decompiling an app that uses connectsdk and it looks like the pairing part wasn't done with connectsdk , it was  calling a Sony hardware library to pair 

I used a similar method. I saw the traffic an app was sending to the TV was using something called ConnectSDK. That's how I found this. Unfortunately I don't know any other libraries that can do what this one does. Others have successfully used it to make apps. That much I know. The devs really just made an amazing tool then left us alone to figure it out :/

**Comment by zamirszn** [comment]
> > > > i ran the sample app and it only connect with limited functionality (only media and volume control works) , i need to implement the remote control feature for my app , ive gone through the docs on how to setup pairing with pin code , still didnt work with my tv , i tested some apps built with connectsdk and i was able to pair and use the remote control with my TV , can anyone help please ? am i missing something ?
> > > 
> > > It's the same for me. I can connect to it and launch some apps but I want keyControl. The docs are not much help for that. I also noticed that it doesn't connect to multiple services for me. Is that the case for you? It connects to either DLNA or DIAL for me. NetCast requires pairing but it won't connect to that.
> > 
> > yup same issue , do you know any other lib that can solve this issue ? this project looks abandoned, I tried decompiling an app that uses connectsdk and it looks like the pairing part wasn't done with connectsdk , it was  calling a Sony hardware library to pair 
> 
> I used a similar method. I saw the traffic an app was sending to the TV was using something called ConnectSDK. That's how I found this. Unfortunately I don't know any other libraries that can do what this one does. Others have successfully used it to make apps. That much I know. The devs really just made an amazing tool then left us alone to figure it out :/

oh ok , if you're building a remote for only your Samsung TV you can use web sockets , I have a demo app for that , I'm building a universal so I'm stuck with using this sdk

**Comment by Avasara** [comment]
> > > > > i ran the sample app and it only connect with limited functionality (only media and volume control works) , i need to implement the remote control feature for my app , ive gone through the docs on how to setup pairing with pin code , still didnt work with my tv , i tested some apps built with connectsdk and i was able to pair and use the remote control with my TV , can anyone help please ? am i missing something ?
> > > > 
> > > > It's the same for me. I can connect to it and launch some apps but I want keyControl. The docs are not much help for that. I also noticed that it doesn't connect to multiple services for me. Is that the case for you? It connects to either DLNA or DIAL for me. NetCast requires pairing but it won't connect to that.
> > > 
> > > yup same issue , do you know any other lib that can solve this issue ? this project looks abandoned, I tried decompiling an app that uses connectsdk and it looks like the pairing part wasn't done with connectsdk , it was  calling a Sony hardware library to pair 
> > 
> > I used a similar method. I saw the traffic an app was sending to the TV was using something called ConnectSDK. That's how I found this. Unfortunately I don't know any other libraries that can do what this one does. Others have successfully used it to make apps. That much I know. The devs really just made an amazing tool then left us alone to figure it out :/
> 
> oh ok , if you're building a remote for only your Samsung TV you can use web sockets , I have a demo app for that , I'm building a universal so I'm stuck with using this sdk

Yea same here. Trying to build a universal app for any TV. I thought about using websockets but this sdk allows others to use it which is what I'm really concerned with honestly. If I can save someone else the amount of headache this has given me, that'll be great lol. I'm reaching out to the devs directly. I'll update you on how it goes soon.

**Comment by zamirszn** [comment]
> > > > > > i ran the sample app and it only connect with limited functionality (only media and volume control works) , i need to implement the remote control feature for my app , ive gone through the docs on how to setup pairing with pin code , still didnt work with my tv , i tested some apps built with connectsdk and i was able to pair and use the remote control with my TV , can anyone help please ? am i missing something ?
> > > > > 
> > > > > It's the same for me. I can connect to it and launch some apps but I want keyControl. The docs are not much help for that. I also noticed that it doesn't connect to multiple services for me. Is that the case for you? It connects to either DLNA or DIAL for me. NetCast requires pairing but it won't connect to that.
> > > > 
> > > > yup same issue , do you know any other lib that can solve this issue ? this project looks abandoned, I tried decompiling an app that uses connectsdk and it looks like the pairing part wasn't done with connectsdk , it was  calling a Sony hardware library to pair 
> > > 
> > > I used a similar method. I saw the traffic an app was sending to the TV was using something called ConnectSDK. That's how I found this. Unfortunately I don't know any other libraries that can do what this one does. Others have successfully used it to make apps. That much I know. The devs really just made an amazing tool then left us alone to figure it out :/
> > 
> > oh ok , if you're building a remote for only your Samsung TV you can use web sockets , I have a demo app for that , I'm building a universal so I'm stuck with using this sdk
> 
> Yea same here. Trying to build a universal app for any TV. I thought about using websockets but this sdk allows others to use it which is what I'm really concerned with honestly. If I can save someone else the amount of headache this has given me, that'll be great lol. I'm reaching out to the devs directly. I'll update you on how it goes soon.

alright thanks , you can reach me on mubaraklawal52@gmail.com please , I'm stuck on the project I'm working on

**Comment by zamirszn** [comment]
> > > > > > i ran the sample app and it only connect with limited functionality (only media and volume control works) , i need to implement the remote control feature for my app , ive gone through the docs on how to setup pairing with pin code , still didnt work with my tv , i tested some apps built with connectsdk and i was able to pair and use the remote control with my TV , can anyone help please ? am i missing something ?
> > > > > 
> > > > > It's the same for me. I can connect to it and launch some apps but I want keyControl. The docs are not much help for that. I also noticed that it doesn't connect to multiple services for me. Is that the case for you? It connects to either DLNA or DIAL for me. NetCast requires pairing but it won't connect to that.
> > > > 
> > > > yup same issue , do you know any other lib that can solve this issue ? this project looks abandoned, I tried decompiling an app that uses connectsdk and it looks like the pairing part wasn't done with connectsdk , it was  calling a Sony hardware library to pair 
> > > 
> > > I used a similar method. I saw the traffic an app was sending to the TV was using something called ConnectSDK. That's how I found this. Unfortunately I don't know any other libraries that can do what this one does. Others have successfully used it to make apps. That much I know. The devs really just made an amazing tool then left us alone to figure it out :/
> > 
> > oh ok , if you're building a remote for only your Samsung TV you can use web sockets , I have a demo app for that , I'm building a universal so I'm stuck with using this sdk
> 
> Yea same here. Trying to build a universal app for any TV. I thought about using websockets but this sdk allows others to use it which is what I'm really concerned with honestly. If I can save someone else the amount of headache this has given me, that'll be great lol. I'm reaching out to the devs directly. I'll update you on how it goes soon.

hello , were you able to get anything ?

**Comment by Avasara** [comment]
> > > > > > > i ran the sample app and it only connect with limited functionality (only media and volume control works) , i need to implement the remote control feature for my app , ive gone through the docs on how to setup pairing with pin code , still didnt work with my tv , i tested some apps built with connectsdk and i was able to pair and use the remote control with my TV , can anyone help please ? am i missing something ?
> > > > > > 
> > > > > > It's the same for me. I can connect to it and launch some apps but I want keyControl. The docs are not much help for that. I also noticed that it doesn't connect to multiple services for me. Is that the case for you? It connects to either DLNA or DIAL for me. NetCast requires pairing but it won't connect to that.
> > > > > 
> > > > > yup same issue , do you know any other lib that can solve this issue ? this project looks abandoned, I tried decompiling an app that uses connectsdk and it looks like the pairing part wasn't done with connectsdk , it was  calling a Sony hardware library to pair 
> > > > 
> > > > I used a similar method. I saw the traffic an app was sending to the TV was using something called ConnectSDK. That's how I found this. Unfortunately I don't know any other libraries that can do what this one does. Others have successfully used it to make apps. That much I know. The devs really just made an amazing tool then left us alone to figure it out :/
> > > 
> > > oh ok , if you're building a remote for only your Samsung TV you can use web sockets , I have a demo app for that , I'm building a universal so I'm stuck with using this sdk
> > 
> > Yea same here. Trying to build a universal app for any TV. I thought about using websockets but this sdk allows others to use it which is what I'm really concerned with honestly. If I can save someone else the amount of headache this has given me, that'll be great lol. I'm reaching out to the devs directly. I'll update you on how it goes soon.
> 
> hello , were you able to get anything ?

Nothing so far. I sent the email to both accounts listed on the GitHub page. No response. I might try to reach them on Twitter next. I don't even know if it's reaching them at all :/

**Comment by Avasara** [comment]
> > > > > > > i ran the sample app and it only connect with limited functionality (only media and volume control works) , i need to implement the remote control feature for my app , ive gone through the docs on how to setup pairing with pin code , still didnt work with my tv , i tested some apps built with connectsdk and i was able to pair and use the remote control with my TV , can anyone help please ? am i missing something ?
> > > > > > 
> > > > > > It's the same for me. I can connect to it and launch some apps but I want keyControl. The docs are not much help for that. I also noticed that it doesn't connect to multiple services for me. Is that the case for you? It connects to either DLNA or DIAL for me. NetCast requires pairing but it won't connect to that.
> > > > > 
> > > > > yup same issue , do you know any other lib that can solve this issue ? this project looks abandoned, I tried decompiling an app that uses connectsdk and it looks like the pairing part wasn't done with connectsdk , it was  calling a Sony hardware library to pair 
> > > > 
> > > > I used a similar method. I saw the traffic an app was sending to the TV was using something called ConnectSDK. That's how I found this. Unfortunately I don't know any other libraries that can do what this one does. Others have successfully used it to make apps. That much I know. The devs really just made an amazing tool then left us alone to figure it out :/
> > > 
> > > oh ok , if you're building a remote for only your Samsung TV you can use web sockets , I have a demo app for that , I'm building a universal so I'm stuck with using this sdk
> > 
> > Yea same here. Trying to build a universal app for any TV. I thought about using websockets but this sdk allows others to use it which is what I'm really concerned with honestly. If I can save someone else the amount of headache this has given me, that'll be great lol. I'm reaching out to the devs directly. I'll update you on how it goes soon.
> 
> hello , were you able to get anything ?

Nothing so far. I sent the email to both accounts listed on the GitHub page. No response. I might try to reach them on Twitter next. I don't even know if it's reaching them at all :/

**Comment by zamirszn** [comment]
> > > > > > > > i ran the sample app and it only connect with limited functionality (only media and volume control works) , i need to implement the remote control feature for my app , ive gone through the docs on how to setup pairing with pin code , still didnt work with my tv , i tested some apps built with connectsdk and i was able to pair and use the remote control with my TV , can anyone help please ? am i missing something ?
> > > > > > > 
> > > > > > > It's the same for me. I can connect to it and launch some apps but I want keyControl. The docs are not much help for that. I also noticed that it doesn't connect to multiple services for me. Is that the case for you? It connects to either DLNA or DIAL for me. NetCast requires pairing but it won't connect to that.
> > > > > > 
> > > > > > yup same issue , do you know any other lib that can solve this issue ? this project looks abandoned, I tried decompiling an app that uses connectsdk and it looks like the pairing part wasn't done with connectsdk , it was  calling a Sony hardware library to pair 
> > > > > 
> > > > > I used a similar method. I saw the traffic an app was sending to the TV was using something called ConnectSDK. That's how I found this. Unfortunately I don't know any other libraries that can do what this one does. Others have successfully used it to make apps. That much I know. The devs really just made an amazing tool then left us alone to figure it out :/
> > > > 
> > > > oh ok , if you're building a remote for only your Samsung TV you can use web sockets , I have a demo app for that , I'm building a universal so I'm stuck with using this sdk
> > > 
> > > Yea same here. Trying to build a universal app for any TV. I thought about using websockets but this sdk allows others to use it which is what I'm really concerned with honestly. If I can save someone else the amount of headache this has given me, that'll be great lol. I'm reaching out to the devs directly. I'll update you on how it goes soon.
> > 
> > hello , were you able to get anything ?
> 
> Nothing so far. I sent the email to both accounts listed on the GitHub page. No response. I might try to reach them on Twitter next. I don't even know if it's reaching them at all :/

I gave up bro , their support is dead even on twitter, i reached out to someone who had similar issue and he had to add support for each remote manually for his app.

**Comment by Avasara** [comment]
> > > > > > > > > i ran the sample app and it only connect with limited functionality (only media and volume control works) , i need to implement the remote control feature for my app , ive gone through the docs on how to setup pairing with pin code , still didnt work with my tv , i tested some apps built with connectsdk and i was able to pair and use the remote control with my TV , can anyone help please ? am i missing something ?
> > > > > > > > 
> > > > > > > > It's the same for me. I can connect to it and launch some apps but I want keyControl. The docs are not much help for that. I also noticed that it doesn't connect to multiple services for me. Is that the case for you? It connects to either DLNA or DIAL for me. NetCast requires pairing but it won't connect to that.
> > > > > > > 
> > > > > > > yup same issue , do you know any other lib that can solve this issue ? this project looks abandoned, I tried decompiling an app that uses connectsdk and it looks like the pairing part wasn't done with connectsdk , it was  calling a Sony hardware library to pair 
> > > > > > 
> > > > > > I used a similar method. I saw the traffic an app was sending to the TV was using something called ConnectSDK. That's how I found this. Unfortunately I don't know any other libraries that can do what this one does. Others have successfully used it to make apps. That much I know. The devs really just made an amazing tool then left us alone to figure it out :/
> > > > > 
> > > > > oh ok , if you're building a remote for only your Samsung TV you can use web sockets , I have a demo app for that , I'm building a universal so I'm stuck with using this sdk
> > > > 
> > > > Yea same here. Trying to build a universal app for any TV. I thought about using websockets but this sdk allows others to use it which is what I'm really concerned with honestly. If I can save someone else the amount of headache this has given me, that'll be great lol. I'm reaching out to the devs directly. I'll update you on how it goes soon.
> > > 
> > > hello , were you able to get anything ?
> > 
> > Nothing so far. I sent the email to both accounts listed on the GitHub page. No response. I might try to reach them on Twitter next. I don't even know if it's reaching them at all :/
> 
> I gave up bro , their support is dead even on twitter, i reached out to someone who had similar issue and he had to add support for each remote manually for his app. 

Damn really? That sucks. Man. Who's the guy? Is the project on GitHub? If the next best thing is to add support manually it'll be great if we have a blueprint at least.

**Comment by zamirszn** [comment]
> > > > > > > > > > i ran the sample app and it only connect with limited functionality (only media and volume control works) , i need to implement the remote control feature for my app , ive gone through the docs on how to setup pairing with pin code , still didnt work with my tv , i tested some apps built with connectsdk and i was able to pair and use the remote control with my TV , can anyone help please ? am i missing something ?
> > > > > > > > > 
> > > > > > > > > It's the same for me. I can connect to it and launch some apps but I want keyControl. The docs are not much help for that. I also noticed that it doesn't connect to multiple services for me. Is that the case for you? It connects to either DLNA or DIAL for me. NetCast requires pairing but it won't connect to that.
> > > > > > > > 
> > > > > > > > yup same issue , do you know any other lib that can solve this issue ? this project looks abandoned, I tried decompiling an app that uses connectsdk and it looks like the pairing part wasn't done with connectsdk , it was  calling a Sony hardware library to pair 
> > > > > > > 
> > > > > > > I used a similar method. I saw the traffic an app was sending to the TV was using something called ConnectSDK. That's how I found this. Unfortunately I don't know any other libraries that can do what this one does. Others have successfully used it to make apps. That much I know. The devs really just made an amazing tool then left us alone to figure it out :/
> > > > > > 
> > > > > > oh ok , if you're building a remote for only your Samsung TV you can use web sockets , I have a demo app for that , I'm building a universal so I'm stuck with using this sdk
> > > > > 
> > > > > Yea same here. Trying to build a universal app for any TV. I thought about using websockets but this sdk allows others to use it which is what I'm really concerned with honestly. If I can save someone else the amount of headache this has given me, that'll be great lol. I'm reaching out to the devs directly. I'll update you on how it goes soon.
> > > > 
> > > > hello , were you able to get anything ?
> > > 
> > > Nothing so far. I sent the email to both accounts listed on the GitHub page. No response. I might try to reach them on Twitter next. I don't even know if it's reaching them at all :/
> > 
> > I gave up bro , their support is dead even on twitter, i reached out to someone who had similar issue and he had to add support for each remote manually for his app. 
> 
> Damn really? That sucks. Man. Who's the guy? Is the project on GitHub? If the next best thing is to add support manually it'll be great if we have a blueprint at least. 

my app is in flutter and I found a Samsung implementation https://github.com/aelshamy/flutter_samsung_remote , it's actually easy to implement

**Comment by Avasara** [comment]
> > > > > > > > > > > i ran the sample app and it only connect with limited functionality (only media and volume control works) , i need to implement the remote control feature for my app , ive gone through the docs on how to setup pairing with pin code , still didnt work with my tv , i tested some apps built with connectsdk and i was able to pair and use the remote control with my TV , can anyone help please ? am i missing something ?
> > > > > > > > > > 
> > > > > > > > > > It's the same for me. I can connect to it and launch some apps but I want keyControl. The docs are not much help for that. I also noticed that it doesn't connect to multiple services for me. Is that the case for you? It connects to either DLNA or DIAL for me. NetCast requires pairing but it won't connect to that.
> > > > > > > > > 
> > > > > > > > > yup same issue , do you know any other lib that can solve this issue ? this project looks abandoned, I tried decompiling an app that uses connectsdk and it looks like the pairing part wasn't done with connectsdk , it was  calling a Sony hardware library to pair 
> > > > > > > > 
> > > > > > > > I used a similar method. I saw the traffic an app was sending to the TV was using something called ConnectSDK. That's how I found this. Unfortunately I don't know any other libraries that can do what this one does. Others have successfully used it to make apps. That much I know. The devs really just made an amazing tool then left us alone to figure it out :/
> > > > > > > 
> > > > > > > oh ok , if you're building a remote for only your Samsung TV you can use web sockets , I have a demo app for that , I'm building a universal so I'm stuck with using this sdk
> > > > > > 
> > > > > > Yea same here. Trying to build a universal app for any TV. I thought about using websockets but this sdk allows others to use it which is what I'm really concerned with honestly. If I can save someone else the amount of headache this has given me, that'll be great lol. I'm reaching out to the devs directly. I'll update you on how it goes soon.
> > > > > 
> > > > > hello , were you able to get anything ?
> > > > 
> > > > Nothing so far. I sent the email to both accounts listed on the GitHub page. No response. I might try to reach them on Twitter next. I don't even know if it's reaching them at all :/
> > > 
> > > I gave up bro , their support is dead even on twitter, i reached out to someone who had similar issue and he had to add support for each remote manually for his app. 
> > 
> > Damn really? That sucks. Man. Who's the guy? Is the project on GitHub? If the next best thing is to add support manually it'll be great if we have a blueprint at least. 
> 
> my app is in flutter and I found a Samsung implementation https://github.com/aelshamy/flutter_samsung_remote , it's actually easy to implement 

Ahh thanks man! I'll try it out. Not sure where to go in regards to my previous project now but guess I'll start a new one. Maybe one day if they come back to ConnectSDK, I'll complete it.
